### ISSUE TITLE
Broken link.

### ISSUE THREAD

**Issue by lukema95** [zeta-chain/example-contracts#103]
The link in the readme file below is broken:

reference:
Please, note that code from this repository is referenced in [the documentation](https://github.com/zeta-chain/zeta-apps/tree/main/apps/frontend/docs-site/docs). When making changes to the code especially when moving files, make sure to update the documentation as well.

The messaging directory contains contracts that demonstrate the ability to send data and value between blockchains using cross-chain transactions, without the need for warpped assets and bridges. Learn more about [cross-chain messaging in the docs](https://www.zetachain.com/docs/developers/cross-chain-messaging/overview/).

**Comment by fadeev** [comment]
Good catch!
